# Generated by Django 2.1.4 on 2019-01-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190101_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artdetail',
            name='art',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='article',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='father',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='gorb',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gorb',
            name='art',
        ),
        migrations.RemoveField(
            model_name='gorb',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ArtDetail',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
        migrations.DeleteModel(
            name='GorB',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
