# Generated by Django 2.1.4 on 2019-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190101_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='write_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
