# Generated by Django 2.1.4 on 2019-01-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190102_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorb',
            name='outcome',
            field=models.BooleanField(default=False),
        ),
    ]
