# Generated by Django 2.1.4 on 2019-01-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190109_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='father',
            field=models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Discuss'),
        ),
    ]
